"""column update

Revision ID: 4e59889c26c3
Revises: f99497651b45
Create Date: 2024-10-02 22:46:04.928917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e59889c26c3'
down_revision = 'f99497651b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client_payment', ['client_payment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_payment_id')

    # ### end Alembic commands ###
