"""Updated Files

Revision ID: 87aba97311e7
Revises: 
Create Date: 2024-08-27 23:29:27.560622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aba97311e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
