"""Updated Files

Revision ID: a03d57f6c4cf
Revises: 87aba97311e7
Create Date: 2024-08-27 23:32:50.795801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03d57f6c4cf'
down_revision = '87aba97311e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
